### ISSUE TITLE
Will pdfium render produce progressive jpgs?

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#18]
Will `pdfium render` produce progressive scan jpgs?
If not, can it be fixed?

I'm guessing this will need to be checked/fixed on two places, go-image and libjpeg-turbo, depending on which lib is used.

**Comment by jerbob92** [comment]
I can add this yeah, but it will only be supported by libjpeg-turbo builds, Go jpeg encode does not support it.

**Comment by msageryd** [comment]
I vote for this feature with turbojpeg =)
It would be awesome. With this feature I can remove Sharp from my file conversion chain. Sharp is a great library (using libvips and turbojpeg), but it's always nice with fewer steps.

**Comment by jerbob92** [comment]
Released in v0.4.0
