### ISSUE TITLE
Alpine binaries slow? How to debug?

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#21]
Thank you soo much for the Alpine binaries. Installation in my Docker image worked flawless with your Docker script.
But something is fishy, and I don't know how to debug.

Here are some timings for the exact same operations on the same file on my Mac vs in Docker on the same Mac. I built my own ARM binary for Mac because I couldn't find it among your release binaries.

Directly on Mac, ARM64 build with CGO but without turboJpeg:
<img width="306" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/e7032004-9b98-4aa4-98a4-f4975faa1f88">

In an Alpine container on the same Mac:
<img width="327" alt="Pasted Graphic" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/f02a1217-3795-47c4-a038-78ca82562206">

There could be a lot of things slowing this down. I'll try to isolate it a bit more. 
Do you have any ideas for debugging?

**Comment by jerbob92** [comment]
I did not build the ARM64 for Mac indeed because it's quite complex to cross-compile CGO applications, I'm kinda waiting for the ARM Mac runner to become available on GitHub to do that: https://github.com/github/roadmap/issues/528

Are you perhaps building this docker image as x64 but running it on arm64 using Rosetta? 

I have tried the musl binary inside and outside the docker container and it's fast for me.

**Comment by msageryd** [comment]
Thanks for the tip.
All of my Dockerfiles has --platform=linux/amd64 for deploying to AWS. I hadn't thougt about this going through Rosetta when I run on M2. I'll try an ARM build. ARM is available at AWS now as well, maybe I can deploy ARM builds all the way.

I can confirm that this is not pdfuim being slow. I made some tests directly in a shell on the Docker image. In fact your new pdfium build is faster than cairo.

pdftocairo:
<img width="498" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/8401083c-cbf7-40a7-ad41-3f22dbf94867">

pdfium WASM build:
<img width="618" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/b9f71f38-a583-4913-8739-8ef87ed9f589">


pdfium CGO + turbojpeg:
<img width="629" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/eec8f407-b346-458c-bc24-c5ad53c7eb7f">

**Comment by jerbob92** [comment]
Nice, thanks for confirming. 
I would not have expected Rosetta to be _that_ slow...

**Comment by msageryd** [comment]
ARM build, massive difference!
<img width="491" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/679ea92b-c02e-482d-a968-838c926773c2">

I didn't get pdfium upd an running yet. Getting this:
<img width="402" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/82c95a4e-bc6b-4303-bca6-f9e9ebaf87d5">

I changed the binaries to ARM, but I have probably missed something. Got to run now, will test more in a couple of ourt.

Thanks!

**Comment by msageryd** [comment]
I just realized that there are no musl-ARM binaries for Linux. Is this as hard to compile as for Mac? Or did you just forget this platform?

**Comment by jerbob92** [comment]
Yeah cross compiling CGO in general is quite complicated, but I didn't really think about musl ARM, I think a bigger problem might be that there is also no musl ARM pdfium binary: https://github.com/bblanchon/pdfium-binaries

**Comment by msageryd** [comment]
Ok, I’ll keep using AMD. It’ll be really slow on my machine, but probably a lot faster on AWS.

Later today I’ll try to deploy a test server with some benchmark tests. I’ll let you know how it goes in this thread.

Sent from my iPhone

On 2 Oct 2023, at 13:31, jerbob92 ***@***.***> wrote:

﻿

Yeah cross compiling CGO in general is quite complicated, but I didn't really think about musl ARM, I think a bigger problem might be that there is also no musl ARM pdfium binary: https://github.com/bblanchon/pdfium-binaries

**Comment by jerbob92** [comment]
I'll check if I can add a Alpine ARM build for pdfium-binaries, if that works out I will look into cross-compiling the CGO binaries.

**Comment by msageryd** [comment]
Some benchmarks... Quite slow on AWS, but this is on a small machine. I don't know how `pdfium info` can be so fast when `render`and `explode` is about the same as on my Mac M2 via Rosetta. The PDF is 7 pages of CAD drawings.
I'll make some cairo tests to get a baseline.

**AMD64 locally, via Rosetta:**
pdfium info: 1.255209 ms
pdfium render 4000px: 13968 ms
pdfium render 120px: 7046 ms
pdfium explode: 400 ms

**AMD64 at AWS Fargate 0.25 vCPU, 2GB ram:**
pdfium info:  0.35 ms
pdfium render 4000px: 14110 ms
pdfium render 120px: 9794 ms
pdfium explode:  395 ms

**Comment by jerbob92** [comment]
Perhaps on Rosetta there is a longer process startup time due to how Rosetta works? In that case you will only see that big of a difference because info doesn't really do that much, while for the other there is much more processing time in the processing. 

I think turbojpeg can be so fast due to multithreading, so it makes sense it's not going to be very fast on a 0.25 vcpu.

**Comment by msageryd** [comment]
Yes, I'll make some tests with more CPU power. pdf2cairo performed even worse. Another win for pdfium..

pdftocairo on the same 0.25 vCPU machine, same PDF file: 32220 ms

**Comment by msageryd** [comment]
**Here are the numbers for the same scenario, but 1 vCPU:**
pdfium info: 0.25 ms
pdfium render 4000px: 3053 ms
pdfium render 120px: 1892 ms
pdfium explode: 62 ms
pdftocairo: 8145

**2 vCPU:**
pdfium info: 0.27 ms
pdfium render 4000px: 3002 ms
pdfium render 120px: 1855 ms
pdfium explode: 86 ms
pdftocairo: 8145 ms

1 vs 2 vCPU is almost identical. As long as I'm only processing one PDF at a time there seems to be no reason for 2 vCPU.

I also tried with 8 vCPU. Cairo seems to utilize more CPUs better. 50% faster. pdfium 30% faster @400px
**8 vCPU:**
pdfium info:  21 ms
pdfium render 4000px:  2077 ms
pdfium render 120px:  1799 ms
pdfium explode:  34 ms
pdftocairo: 4079 ms

**Comment by msageryd** [comment]
Cairo takes better advantage of more CPUs, but even @8vCPU cairo isn't as fast at pdfium @1vCPU. It makes more sense to spin up multiple 1vCPU containers with pdfium when the load increases (i.e. multiple renders concurrently).

I there will be ARM binaries avaliable I'll make the same tests again.

Closing this with the conclusion:
- Don't run pdfium on 0.25 vCPU
- No real gains to be had over 1 vCPU
- i.e. 1 vCPU is sweet spot for now.

**Comment by jerbob92** [comment]
Small update on the Alpine ARM support for pdfium-binaries:
 - I got arm64 (aarch64) to compile pretty easily
 - I'm getting some compile errors on normal arm, so that will require some more work, maybe I'll try to get arm64 merged in first and then look into arm later.

**Comment by msageryd** [comment]
<img width="525" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/60cea5fc-b9e5-4057-bf7b-6234bba844f6">

**Comment by msageryd** [comment]
Just some more info on this, for anyone landing on this thread.
As of Docker Desktop for Mac 4.25, the Rosetta support is buildt in. 

My Alpine AMD64 containers are ripping through pdfium calls like never before on Apple Silicone. I don't have the setup for the above performance tests, but I can visually see that the performance is vastly improved.

<img width="813" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/1a4ebf0c-b0cf-4626-9f3c-f1a8b17dfabd">

**Comment by msageryd** [comment]
Another update on performance.
My PDF files often consist of many pages. I'm now shopping up pages in smaller page-spans and spawning multiple pdfium-cli processes. Currently I'm using max 10 processes. The penalty for starting a process pays off very fast. The stdout solution for pdfium-cli lends itself great for this concept. My conversion speeds for larger documents are now really great, and I can always throw in more CPU cores if needed.
