### ISSUE TITLE
What units do I get for page dimensions from pdfium-cli info 

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#22]
The few documents I have tried seems to output dimensions in millimeters, i.e. approx. 210 x 297 for A4.

Will this be true for all PDF? 
Or is it possible that a PDF can be created with other dpi than 1/72?

When identifying page sizes with Poppler I used to multiply by 72 and divide by 25.4, but this calculation already seems to be performed in `pdfium info`

**Comment by msageryd** [comment]
Oops, sorry. 
I misread the output, disregard the above flase information.

I see now that Width and Height in the Pages array is expressed in "points".

My only outstanding question is not a Pdfium question, but someone might know:
- Is it possible that a PDF can be created with other dpi than 1/72?

**Comment by jerbob92** [comment]
> Is it possible that a PDF can be created with other dpi than 1/72?
As far as I know, no. The value pdfium returns is always points and have not seen any other value that might indicate some other DPI.

**Comment by jerbob92** [comment]
What I'm reading is that it might be different since PDF 1.6, which is configured by the UserUnit on a page object. This value will be in multiples of 1/72. I can't find "UserUnit" in the source code of pdfium anywhere, so I doubt if we can get that information in pdfium right now.

**Comment by jerbob92** [comment]
I have looked around and it looks like almost nobody is using this, and that the implementation in Adobe itself is even kinda weird, so no idea if you should take this into account.

However, there was an open issue report for pdfium about it, so I added my comment to it: https://bugs.chromium.org/p/pdfium/issues/detail?id=734

If it's added in pdfium, I'll make sure it gets added to go-pdfium and pdfium-cli.

**Comment by msageryd** [comment]
Thanks for looking into this. I'm guessing that I would have encountered this while using Poppler as well, but I haven't. My guess is that it's extremely rare that UserUnit is used.
