### ISSUE TITLE
Is the output order of pages in stdout reliable?

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#23]
Will the order of the files in stdout always be in ascending page order, even if `pages` is not ascending?

Ex:
Will these commands consistently output the files in page order 1,2,3,4,5?
`pdfium-cli render --pages "1-5" --file-type "jpeg" - -`
`pdfium-cli render --pages "2,5,4,3,1" --file-type "jpeg" - -`
`pdfium-cli render --pages "2-5,1" --file-type "jpeg" - -`

**Comment by jerbob92** [comment]
Yes, the pages are calculated per page range (a page range is divided by a comma and can be a single page number or a range, and a page number can be a number, keyword (first and last) and reversed with r). Per calculated page number it will check if it's a duplicate. So the given commands will result in:

- 1,2,3,4,5
- 2,5,4,3,1
- 2,3,4,5,1

**Comment by msageryd** [comment]
Thanks, thats great to know.

A possible bug could sneak up if the **user/client** and **pdfium-cli** has implemented a `pages` interpreter differently. I'll only use use comma separated pages flags to ensure there will be no room for different interpretations.

A way to mitigate any discrepancies would be to add `--pages` flag to `pdfium-cli info`. This way the user could run the pages string through the info command and receive an array with with the correct pages in the correct order.

Another solution could me to add a flag to the `render` and `explode` commands to get a JSON array as the first "file" in the stdout stream. This should output an integer array of **page number** (1-based) or **page index** (0-based)  as per pdfium-cli's pages interpreter.

**Comment by jerbob92** [comment]
Yeah if you get the page ranges from somewhere else it's probably always best to calculate the pages yourself and just pass them as single pages with a comma in the page ranges option.

The pages option to the info command is a good idea indeed, will implement that, the second option sounds overly complex for the issue.

**Comment by msageryd** [comment]
Great.
I'll leave this issue open if you want to reference a PR here. Feel free to close the issue otherwise.

**Comment by msageryd** [comment]
After some thought, I actually don't think I can use the `info --pages` concept.

I'm trying to keep my streams as streams, i.e. not filling up buffers with complete files. My initial stream comes from S3. Before I can feed this stream to `pdfium render --pages ..`, I need to specify my pages. If I would derive the pages string from the output of `pdflium-cli info` I would have to consume the complete S3 stream into a buffer before sending it off to `render`. 

If I have to buffer the whole file it defeats the idea of streaming.

As I said, I'm good anyway since I will always have a comma separated string with single page numbers.
