### ISSUE TITLE
Is the whole file needed for "pdfium info"

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#25]
I have a small problem. I don't like my current solution and wonder if `pdfium info` could work with only the first part of a file?

I need to render specific pages from a PDF file. To identify these pages I need to run `pdfium info`. As of now I'm feeding the whole file into pdfium, i.e. I need to consume the whole stream into a buffer and send the buffer to `pdfium info`.

When I have the page info I'm creating a stream out of the buffer to feed `pdfium render`. Like this:

<img width="656" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/ee3eabfb-4ba3-4fb9-9558-4271628b4e36">

Does `pdfium info` need the whole file, or is the pages information available early in the file? Would the following be possible?
<img width="649" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/926aa356-8720-4267-983e-46f536bfdb42">

**Comment by jerbob92** [comment]
Sadly, that is not possible with the way PDF files are structured. The table that says where objects can be found and where the root object is are at the end of the file: https://www.google.com/amp/s/blog.idrsolutions.com/what-are-pdf-xref-tables/amp/

Normally this wouldn't be a problem with pdfium because with real files it can just seek through the file, but this is not possible with stdin, so it needs to consume the full stream before it can read the xref table.

Maybe a tmp file would be a solution for you? There are other ways but they probably require a more direct integration (with bi-directional communication).

**Comment by jerbob92** [comment]
One idea that I do have: if the file comes directly from S3, I can also add URL support to the tool, if S3 supports byte range requests, it's very similar to seeking. Pdfium does have a way to implement these byte range requests.

**Comment by msageryd** [comment]
Would other pdfium commands benefit from having a temp file as input, or is it just `info` which gets faster due to the file seeking?

**Comment by jerbob92** [comment]
Any command would benefit from that, as it means it doesn't have to load the full file into memory. Commands that do not consume the full pdf (like info, or partial renders) benefit the most though.

**Comment by msageryd** [comment]
Thanks.
I'll make some timing tests with a temp file as input.

**Comment by msageryd** [comment]
Thanks.
I'll make some timing tests with a temp file as input.

**Comment by jerbob92** [comment]
Perhaps you can use a tmpfs?

**Comment by msageryd** [comment]
I have made some timing tests and concluded that the stream/buffer/file handling is definitely not the slow part. A 50 page PDF from where I convert 30 pages differs only a couple of percent in total time between the concepts.

Since there seems to be no time penalty for working with files on disk, I'll go that way. It's not uncommon to process the same PDF file several times after some user input inbetween. If I keep the files on disk I can cache them there for a while and save some round-trips to S3 if a file is on local disk when it's needed again.

tempfs is a great idea, but it has the drawback that I would use precious RAM in my containers and I won't get the benefit of caching files locally since I'd have to unlink them directly.

**Comment by jerbob92** [comment]
Yeah I would also say that the file has to be really big or the disk really slow for that to matter too much, the rendering is definitely the slow part.

We could still look into the byte-range requests by fetching the needed parts directly from S3, but then you have to deal with network latency for every byte-range request, which might not be worth it.
