### ISSUE TITLE
Corrupt JPG files when using multiple instances

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#27]
I'm getting really weird errors when I'm pushing pdfium-cli hard. Locally on my Macbook M2Max I have a hard time to push it to this limit, but I can reproduce the error.

On my AWS Fargate containers I don't need to push much to get the error.

- I cannot reproduce the error when I let pdfium write the output files directly to disk.
- When I use stdout to read the files separated by a delimiter I get into problems, but not always.

My setup:
- PDF file with 150 pages
- pdfium command 
`render ./inputFile.pdf - --max-width 4000 --max-height 4000 --pages "1-50" --std-file-delimiter myDelimiter`
- myDelimiter is two dashes and a guid: `--9c354adf-6110-4016-aae7-e48740e7192c`

- I'm spawning 30 parallel pdfium processes with the exact same command from Node.js.
- On each "file", I directly write the collected chunks to disk in this test environment.
- The disk writing has nothing to do with the bug, the below buffer data is logged before writing to file
- 50 pages 30 times gives me 1500 jpg files.
- Out of those files, about 1% are corrupt.

I'm naming the files with page number, so I can compare a corrupt file with the exact same non-corrupt page. I discovered that the difference is that my corrupt files has an extra byte `01` at the beginning. The corrupt file is one byte larger than the non-corrupt files.

Here are three versions of page 3, rendered from three different pdfium processes. The first buffer is from the corrupt file. I have indented the the non-corrupt files one byte so you can see that they are identical apart from the first byte.
```
<Buffer 01 01 01 01 02 01 01 01 02 02 02 02 02 04 03 02 02 02 02 05 04 04 03 04 06 05 06 06 06 05 06 06 06 07 09 08 06 07 09 07 06 06 08 0b 08 09 0a 0a 0a 0a ... 1207144 more bytes>
<Buffer    01 01 01 02 01 01 01 02 02 02 02 02 04 03 02 02 02 02 05 04 04 03 04 06 05 06 06 06 05 06 06 06 07 09 08 06 07 09 07 06 06 08 0b 08 09 0a 0a 0a 0a 0a ... 1207143 more bytes>
<Buffer    01 01 01 02 01 01 01 02 02 02 02 02 04 03 02 02 02 02 05 04 04 03 04 06 05 06 06 06 05 06 06 06 07 09 08 06 07 09 07 06 06 08 0b 08 09 0a 0a 0a 0a 0a ... 1207143 more bytes>
```

I'm literally ripping my hair.. Cannot understand why Node would add a byte to a buffer sporadically, and only do so under high load.

Could this be a bug in pdfium?
I really hope so, because I cannot come any further with this.

Yes, I'm the one resonsible for splitting stdout into separate files. I do this by searching in each chunk for my delimiter. I absolutely thought this was an error in my code. But I can't find it. The code is quite simple, and I cannot understand how this code could behave differently 1% of the time.

Here is the important part of my code.
```
      child.stdout.on('data', (chunk) => {
        const delimiterIndex = chunk.indexOf(FILE_DELIMITER, 0, 'binary');

        if (delimiterIndex > -1) {
          //We found a delimiter
          //Finish writing to the current file up until the delimiter
          buffers.push(chunk.slice(0, delimiterIndex));
          handleOutput({
            fileBuffer: Buffer.concat(buffers),
            fileIndex,
          });

          //Start a new file
          buffers = [];
          fileIndex++;

          chunk = chunk.slice(delimiterIndex + FILE_DELIMITER.length + 1, chunk.length);
        }
        buffers.push(chunk);
      });

      child.on('close', async (code) => {
        handleOutput({
          fileBuffer: Buffer.concat(buffers),
          fileIndex,
        });
        resolve();
      });
```

**Comment by msageryd** [comment]
Update..
I have now isolated this a bit more. I think Pdfium is off the hook.

**Isolating pdfium's part of the work:**
Spawn multiple parallel pdfium processes and send the output stream to files, one file for each process. I.e. each file is a concatenated stream of 50 jpgs and delimiters. This is performed without Node.js, i.e. no risk of misusing child_process.spawn or stumbling upon a bug in child processes.

Bash script to generate 50 files of 50 concatenated jpg files each in parallel.
```
for i in {1..50}; do
  pdfium render "../test/resources/a-binder.pdf" - --max-width 4000 --max-height 4000  --pages "1-50" --std-file-delimiter myDelimiter > "../test/output/file_$i.stream" &
done

wait

```

Then I processed each file in Node in the exact same way I usually process stdout from the Pdfium child process.

I have now decoupled from the child_process code.

**Result: No corrupt files!!**
I have ran the above test a couple of times and didn’t catch a single corrupt jpg file. I think we can conclude that pdfium is not at fault, nor is my code for parsing and splitting the concatenated stream.

I'm closing this issue, since it's most likely not related to Pdfium.

**Comment by jerbob92** [comment]
Thanks for the thorough report and update! Still curious what the cause is when you have found the issue.

**Comment by msageryd** [comment]
Next step..

I did the same isolation test as above, but instead of using bash I used Node child_process. Within Node.js I piped stdout from each child process into a concatenated file. I then parsed these files with another Node script, i.e the same code as I use for parsing stdout directly from the child process. The only difference now is that I'm doing a stopover at the file system.

**Result: No currupt files**

Conslusion:
- There is no problem spawning multiple pdfium processed from Node

**A: This process outlined (no corrupt files):**
1. Run multiple pdfium in parallel from Node and output to concatenated stream
2. pipe each stream to files on disk
3. read each concatenaded file from Node and separate the jpg files

**B: The original process outlined (corrupt files):**
1. Run multiple pdfium in parallel from Node and output to concatenated stream
2. _no disk files involved at this stage_
3. process each stream directly in Node and separate the jpg files

Something is clearly happening in my code when I process the stream directly (B). At first I thought this might be an obscure case of back pressure in the streams. But reading directly from files (A) is even faster than processing the stream directly from pdfium, so a back pressure problem would arise even more so in case B.

**Comment by msageryd** [comment]
Hm.. I'm now deep into the stream.. reading, searching, ripping my hair...

I found that after every delimiter, there is a chr(10). 
Does pdfium-cli put a linefeed after each delimiter?

If I account for the extra linefeed everything works great. I really don't understand why most of the jpg files turns out ok even if I don't account for the extra linefeed.

Q: Should I rely on this extra linefeed after the delimiter, or is this a bug in pdfium-cli?

**Comment by jerbob92** [comment]
Yes, see this: https://github.com/klippa-app/pdfium-cli/blob/main/cmd/render.go#L233-L235
It adds a newline before and after the delimiter.

**Comment by msageryd** [comment]
Ok, thanks.
What's the rationale behind this?

Maybe this is how multipart data in html works? If that's the case I won't argue, but otherwise I'd prefer the delimiter to be exactly what I say it should be by providing it as an argument to pdfium.

If you want to keep the linefeeds I strongly think this should be documented. Otherwise it's quite hard to use this feature without reading the go source code.

**Comment by jerbob92** [comment]
I agree it should be documented. It's mainly to follow multipart/form-data and to keep it clear where the data is separated when you view the raw data.

**Comment by msageryd** [comment]
Makes sense.
If this is how multipart data is separated you should do the same.

Thank you again. 
Closing this again. No more reopening, I promise =)

**Comment by msageryd** [comment]
During this long debugging session, my collegue brought me a T-shirt =)
