### ISSUE TITLE
Blank output

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#30]
I have encountered a PDF file from which **pdfium-cli** renders a blank jpg.
**pdftocairo** manages to peel out the correct jpg from the same file.

The file shows up correctly when previewed with **Chrome**. Chrome uses pdfium, doesn't it?

Any clue of what the problem might be?
The pdf is attached here.
[testfile.pdf](https://github.com/klippa-app/pdfium-cli/files/13604646/testfile.pdf)

**Comment by jerbob92** [comment]
I was able to reproduce this, it has to do with annotations. If I add the flag `FPDF_RENDER_FLAG_ANNOT` to the render instruction then everything shows up. Kinda odd that this was added as annotation. 

I can add a CLI option to enable the rendering of annotations, but I'm not sure if you always want to render annotations?

**Comment by msageryd** [comment]
I almost never want the annotations, but if it's easy to add an option I think it might be handy sometimes.

**Comment by jerbob92** [comment]
The `--render-annotations` flag has been added in [v0.6.0](https://github.com/klippa-app/pdfium-cli/releases/tag/v0.6.0).
