### ISSUE TITLE
Feature request: add jpg render options

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#32]
It would be really great if it was possible to add arguments for the jpg scaling. I'm creating two jpg versions from my pdf pages, one medium resolution file and one thumbnail.

The thumbnail is created like this:
`pdfium render input.pdf output.jpg --max-height 120 --max-width 120 --file-type jpeg`

The 120px jpg files are quite "blotchy". My current workaround is to not use pdfium-cli for this, and instead scale the medium jpg file with the Sharp library. If I could add parameters to the jpg rendering (I suppose those should just be forwarded to libjpg), I'm guessing that I could get nicer thumbnails.

This is a thumbnail from pdfium-cli:
<img width="124" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/83caab31-0ab9-4326-bdcc-39638cf97a85">

This is the same input pdf, but this file is scaled down with Image Magic:
<img width="126" alt="image" src="https://github.com/klippa-app/pdfium-cli/assets/4483085/70a063bc-f517-4490-92a7-8c22a23bc0db">

**Comment by msageryd** [comment]
I have now done some testing with different interpolation engines. I'm not able to reproduce the blotchy look of the pdfium rendered thumbnail with any other engine.

I suppost this problem has nothing to do with choosing Lanczos3 over Nearest neighbor. I think the pdfium renderer is simply a bit naive when scaling down vector graphics to lower resoutions.

I'm good with my solution to resize the thumbnail outside of pdfium (with Sharp). If there is a simple fix to pdefium-cli, I think it would be good for the project. But I don't need this function so please go ahead and close this issue if you want.

**Comment by jerbob92** [comment]
I think this has to do with the vector graphics rendering in pdfium that might have some minimum thickness for lines? If you want you can open an issue with pdfium, I'll close this one here for now.

**Comment by msageryd** [comment]
No need for me. I'm using Sharp for other stuff, so I'm fine without pdfium thumbnails.

But thumbnails for PDF pages is a quite common use case. I'm surprised that pdfium doesn't handle this better.

**Comment by jerbob92** [comment]
Yeah me too, still might be good to just drop it by them to see what they think.
