### ISSUE TITLE
Form content not rendered

### ISSUE THREAD

**Issue by josiasmontag** [klippa-app/pdfium-cli#47]
The rendered images result misses form elements. 
This can be fixed by calling the method `FPDF_FFLDraw` of pdfium.

I think the default should be to include form content because one does not expect that this gets removed when rendering PDFs.

**Comment by jerbob92** [comment]
I do not agree that form content should be rendered by default, just like annotations are also not rendered by default. 
Rendering forms require multiple operations to initialize/exit/render the form (`FPDFDOC_InitFormFillEnvironmentFPDFDOC_ExitFormFillEnvironment`, `FORM_OnAfterLoadPage`, `FORM_OnBeforeClosePage` and `FPDF_FFLDraw`) which could affect performance.  

I can include a flag (like annotations) that enables rendering of forms.

**Comment by msageryd** [comment]
I also agree that this should not be the default. 

I also have a follow up question about annotations. Most of my PDFs do not have annotations, but I'm rendering annotations always so I won't miss them. Will this decrease performance like you describe for form rendering?

**Comment by jerbob92** [comment]
@msageryd rendering annotations is done by giving an extra flag `FPDF_RENDER_FLAG_ANNOT` (`FPDF_ANNOT` in pdfium codebase) to `FPDF_RenderPageBitmap`. Internally this does the following in pdfium:

```
  if (flags & FPDF_ANNOT) {
    auto pOwnedList = std::make_unique<CPDF_AnnotList>(pPage);
    CPDF_AnnotList* pList = pOwnedList.get();
    pContext->m_pAnnots = std::move(pOwnedList);
    bool bPrinting =
        (flags & FPDF_PRINTING) ||
        pContext->m_pDevice->GetDeviceType() != DeviceType::kDisplay;

    // TODO(https://crbug.com/pdfium/993) - maybe pass true here.
    const bool bShowWidget = false;
    pList->DisplayAnnots(pContext->m_pContext.get(), bPrinting, matrix,
                         bShowWidget);
  }
```

If there are no annotations, `DisplayAnnots` doesn't really do anything, so I don't think it decreases performance if there are no annotations.

**Comment by jerbob92** [comment]
Closing due to lack of reply.
